name: primeira-pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  

jobs:
  hello-world:
    name: "Hello World"
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World"
      - name: "Print More Things"
        run: |
          echo "Congratulations!"
          echo "You have created a new workflow."
  node-version:
      name: "Print Node Version"
      runs-on: ubuntu-latest
      steps:
        - name: "Check Node Version"
          run: |
            echo "Versao atual:"
            node --version