name: primeira-pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  

jobs:
  hello-world:
    name: "Hello World"
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World"
      - name: "Print More Things"
        run: |
          echo "Congratulations!"
          echo "You have created a new workflow."